language: python
python:
- 3.5
before_install:
- git clone https://github.com/tamplier77/dbd-test
- cd dbd-test
- docker-compose up
script:
- curl http://localhost:5000/
dd:
  secure: BiAhZpta2kDsHISuZsXxT1OSPLMGmrYU+QIYW8wFtfBZTUYew3CN8Nkj/StbBvgGSRYG1CALV4FDWc07IrOMwwRo5doCcdRvBS6waeomGaAFuQ7MoLaPmpc198i3/sYyPOaITtWv1DnWkjGypKlYNlD7r2EBLfkHAJU9B3/3DzZ22QxrFVrAxit4rJhtHZRBLD6aVbPJphAAUpop8m7MG7lLNewAZjHLgSGJRpNR+5BPFLQ2OjpLPuGv6maqnXEqN3IY2fO0GgA2PK8z4MLRwbX5STArQmZYn9/zDv0kOh6NDglQB1QFv2mh34TlqIRfW+dZvQ543PS5ocrSOaQ81Nw+R0sDhwau3La46P6g0UYgphdeRtXJGTuvruBIig4gbX3FrJfbGvxOGwSElLj5hmf4obTeSGA+ufslWHbqcPbZc4Vfurf0GYHQPEiY+K51uQNZTHNkUpcbQnWLvD1erEcKAK4q/wXWNERLP0cqcuwetTJ9Knlnm8ouWr75396NKgu0afBP6D+fi9Fzziv31SqISJARf99PZQGJnqkSAdUepnTUU8+/8uyGdMLknMkaNRVwY6QPF+qhHP9weEL0eDmvQmNnNCCEImUpEmctx/acUtXYSLXJ4tBcMyPR8tV829Y39XKP/YBBFzLAXx5CAhjBRQ+HeS/sJZqtJIy3znQ=
